import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,realpathSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHub} from '../src/core/hub.js';
import {createBrokerClient} from '../src/net/broker-client.js';
import {workspaceDigest} from '../src/core/room-workspace.js';
import {createServer} from '../../intent-broker/src/http/server.js';
import {createBrokerService} from '../../intent-broker/src/broker/service.js';

test('real broker HTTP tickets apply KSwarm mapping, dispatch, cancellation and historical result',async t=>{
  const root=realpathSync(mkdtempSync(join(tmpdir(),'kswarm-workspace-e2e-')));
  const workFolder=join(root,'任意 名称');mkdirSync(workFolder);
  const broker=createBrokerService({dbPath:join(root,'broker.sqlite')});
  const server=createServer({broker,roomService:broker.room,roomDesktopToken:'desktop-test',roomKSwarmToken:'kswarm-test'});
  await server.listen(0,'127.0.0.1');
  t.after(async()=>{await server.close();broker.close();});
  const base=`http://127.0.0.1:${server.address().port}`;
  let incarnation;
  const call=async(path,body)=>{
    const response=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json','x-intent-broker-room-token':'desktop-test',...(incarnation?{'x-intent-broker-host-incarnation':String(incarnation)}:{})},body:JSON.stringify(body)});
    const value=await response.json();assert.equal(value.ok,true,JSON.stringify(value));return value;
  };
  const roomId=(await call('/rooms',{title:'shared',memberAgentIds:['worker']})).room.roomId;
  const path=`/rooms/${roomId}/workspace`;
  const host=(await call(path+'/register-host',{startupId:'boot'})).host;incarnation=host.hostIncarnation;
  let config=(await call(path+'/begin-change',{expectedRevision:0,requestId:'bind',payloadDigest:'a'.repeat(64)})).config;
  config=(await call(path+'/commit-binding',{expectedRevision:config.revision,operationId:'bind',workspaceId:'w',bindingId:'b',payloadDigest:'a'.repeat(64)})).config;
  config=(await call(path+'/activate-binding',{expectedRevision:config.revision,operationId:'bind'})).config;
  const client=createBrokerClient({brokerUrl:base,participantId:'kswarm',roomSystemToken:'kswarm-test'});
  const hub=createHub({silent:true,dataDir:join(root,'state.json'),projectStorageRoot:join(root,'managed'),brokerClient:client});
  t.after(()=>hub.closePersistence());
  const project=hub.createProject({id:'p',name:'p',goal:'g',poAgent:'po',members:['worker']});
  hub.handleCreateTasks('p',[{id:'a',title:'a',assignedAgent:'worker'}],'po');hub.handleApprove('p');
  project.primaryRoomId=roomId;
  const payload={projectId:'p',roomId,workspaceId:'w',originHostId:host.hostId,bindingId:'b',generation:config.generation,expectedProjectRevision:project.projectRevision,workFolder,artifactsDir:workFolder};
  const payloadDigest=workspaceDigest('mapping',payload);
  await call(path+'/project-fence',{expectedRevision:config.revision,projectId:'p',operationId:'map'});
  const ticket=(await call(path+'/mapping-ticket',{projectId:'p',operationId:'map',payloadDigest,expectedProjectRevision:project.projectRevision})).ticket;
  const mapped=await hub.applyWorkspaceMapping('p',{ticketId:ticket.ticketId,operationId:'map',payload,payloadDigest},{requestSource:'user'});
  assert.equal(mapped.ok,true,JSON.stringify(mapped));assert.equal(mapped.receipt.status,'applied');
  assert.equal(existsSync(join(workFolder,'artifacts')),false);
  const claim=(await call(path+'/acquire',{logicalAgentId:'worker',runId:'run-a',executorInstanceId:'ex-a',contextScope:{kind:'project',projectId:'p'},projectMappingRevision:mapped.mapping.mappingRevision,capability:{contextVersion:1,resultVersion:1,releaseVersion:1,canSetCwd:true,canTrackChildren:true,canRelease:true}})).claim;
  await call(path+'/ack',{...claim,logicalAgentId:'worker',claimId:claim.claimId,actualCwd:workFolder,cwdVerified:true});
  const dispatched=await hub.dispatchWorkspaceTask('p',{taskId:'a',claimId:claim.claimId});
  assert.equal(dispatched.ok,true,JSON.stringify(dispatched));assert.deepEqual(dispatched.dispatched,['p__a']);
  hub.handleAcceptTask('p','a','worker','run-a');hub.handleProgress('p','a','started','worker','run-a');
  const result={summary:'The work was completed and this detailed report records the verification and the finished output.'};
  const resultDigest=workspaceDigest('project-result',{projectId:'p',taskId:'p__a',claimId:claim.claimId,runId:'run-a',result});
  const resultTicket=(await call(path+'/agent-ticket',{logicalAgentId:'worker',claimId:claim.claimId,submissionId:'s',payloadDigest:resultDigest})).ticket;
  await call(path+'/cancel',{claimId:claim.claimId});
  assert.equal((await hub.authorizeWorkspaceDelivery('p','a')).ok,false);
  const applied=await hub.submitWorkspaceTaskResult('p',{taskId:'a',claimId:claim.claimId,ticketId:resultTicket.ticketId,submissionId:'s',payloadDigest:resultDigest,result});
  assert.equal(applied.ok,true,JSON.stringify(applied));
});
